"""
============================================================
ESP32-P4 AI Voice Assistant
AI Server - Data & Response Models

Defines Pydantic schemas for STT, LLM, TTS, and the unified
Assistant pipeline communication between ESP32-P4 and FastAPI.
============================================================
"""

from typing import List, Optional
from pydantic import BaseModel, Field


# ============================================================
# 1. Speech-to-Text (Whisper) Models
# ============================================================

class TranscribeResponse(BaseModel):
    """
    Response returned by the /transcribe endpoint.
    Matches your ESP32 cJSON parsing logic for {"text": "..."}.
    """
    text: str = Field(..., description="Transcribed speech text")
    language: Optional[str] = Field("en", description="Detected spoken language")
    duration_seconds: Optional[float] = Field(0.0, description="Duration of processed audio in seconds")
    processing_time_ms: Optional[float] = Field(0.0, description="Time taken to transcribe in milliseconds")


# ============================================================
# 2. LLM Chat (DeepSeek) Models
# ============================================================

class ChatMessage(BaseModel):
    """
    Represents a single message turn in a conversation history.
    """
    role: str = Field(..., description="Role of the speaker: 'user' or 'assistant'")
    content: str = Field(..., description="Text content of the message")


class ChatRequest(BaseModel):
    """
    Request payload for the /chat endpoint.
    """
    message: str = Field(..., description="Latest user prompt / recognized speech")
    history: Optional[List[ChatMessage]] = Field(default_factory=list, description="Optional conversation history for context")


class ChatResponse(BaseModel):
    """
    Response returned by the /chat endpoint.
    Matches ESP32 cJSON parsing for {"response": "..."}.
    """
    response: str = Field(..., description="AI text reply generated by DeepSeek")
    model_used: Optional[str] = Field("deepseek-chat", description="Name of the LLM model used")
    processing_time_ms: Optional[float] = Field(0.0, description="LLM inference latency in milliseconds")


# ============================================================
# 3. Text-to-Speech (Kokoro) Models
# ============================================================

class TTSRequest(BaseModel):
    """
    Request payload for the /tts endpoint when requesting audio synthesis.
    """
    text: str = Field(..., description="Text to synthesize into speech")
    voice: Optional[str] = Field("af_heart", description="Kokoro voice ID to use")
    speed: Optional[float] = Field(1.0, description="Speech playback speed multiplier")


class TTSMetadataResponse(BaseModel):
    """
    Metadata about the synthesized audio stream.
    Useful if sending JSON headers before raw PCM streaming.
    """
    sample_rate: int = Field(16000, description="Audio sample rate in Hz")
    channels: int = Field(1, description="Number of audio channels (1 for mono)")
    bits_per_sample: int = Field(16, description="Bit depth (16-bit PCM)")
    format: str = Field("pcm_s16le", description="Audio encoding format")
    total_samples: Optional[int] = Field(0, description="Total number of audio samples generated")


# ============================================================
# 4. Unified Assistant Pipeline Models
# ============================================================

class AssistantResponse(BaseModel):
    """
    Unified JSON response payload for the /assistant endpoint.
    Contains both the STT recognition results and the LLM reply.
    """
    status: str = Field("success", description="Pipeline execution status: 'success' or 'error'")
    recognized_text: str = Field(..., description="What the Whisper model heard from the microphone")
    ai_reply: str = Field(..., description="What the DeepSeek LLM replied")
    audio_stream_url: Optional[str] = Field(None, description="Optional URL to fetch the TTS PCM audio if not streamed directly")
    total_latency_ms: Optional[float] = Field(0.0, description="Total end-to-end processing time in milliseconds")


# ============================================================
# 5. Generic Error & Status Models
# ============================================================

class ErrorResponse(BaseModel):
    """
    Standardized error response for API failures.
    """
    status: str = Field("error", description="Always 'error'")
    detail: str = Field(..., description="Detailed error message describing what failed")
    error_code: Optional[int] = Field(None, description="Internal error code for debugging")
