"""
============================================================
ESP32-P4 AI Voice Assistant
AI Server - Kokoro Text-to-Speech Service

Synthesizes conversational AI responses into clean 16-bit 
mono PCM audio. Features native resampling to 16 kHz and 
chunked streaming for low-latency playback on the ESP32.
============================================================
"""

import time
import logging
import numpy as np
from typing import Generator, Optional, Tuple

import config

# Configure logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("KokoroService")

try:
    from kokoro import KPipeline
    KOKORO_AVAILABLE = True
except ImportError:
    KOKORO_AVAILABLE = False
    logger.error("⚠️ 'kokoro' package not found. Run: pip install kokoro soundfile")


class KokoroService:
    """
    Singleton service class for generating speech audio using Kokoro-82M.
    """
    _instance: Optional["KokoroService"] = None
    _pipeline: Optional["KPipeline"] = None
    _native_sample_rate: int = 24000  # Kokoro always generates 24 kHz audio

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(KokoroService, cls).__new__(cls)
            cls._instance._initialize_pipeline()
        return cls._instance

    def _initialize_pipeline(self):
        """
        Initializes the Kokoro TTS pipeline.
        Called automatically once during server startup.
        """
        logger.info("===========================================")
        logger.info("Initializing Kokoro TTS Engine...")
        logger.info(f"Target Voice       : '{config.KOKORO_VOICE}'")
        logger.info(f"Target Sample Rate : {config.AUDIO_SAMPLE_RATE} Hz (ESP32 PCM)")
        logger.info("===========================================")

        if not KOKORO_AVAILABLE:
            logger.error("Kokoro TTS library is not installed. TTS generation will fail!")
            return

        start_time = time.time()
        try:
            # 'a' initializes American English phonemization (misaki G2P)
            # Use 'b' for British English if preferred
            self._pipeline = KPipeline(lang_code='a')
            load_time = round(time.time() - start_time, 2)
            logger.info(f"Kokoro TTS Pipeline loaded successfully in {load_time}s!")
        except Exception as e:
            logger.error(f"Failed to initialize Kokoro pipeline: {e}")

    def _resample_and_quantize(self, audio_float32: np.ndarray) -> bytes:
        """
        Converts Kokoro's native 24 kHz float32 array (-1.0 to 1.0) into 
        16 kHz signed 16-bit PCM bytes (-32768 to 32767) expected by the ESP32.

        :param audio_float32: Raw float32 numpy array from Kokoro
        :return: Raw bytes ready for HTTP transmission
        """
        if len(audio_float32) == 0:
            return b""

        # 1. Fast Linear Interpolation Resampling (24000 Hz -> 16000 Hz)
        target_sr = config.AUDIO_SAMPLE_RATE
        if self._native_sample_rate != target_sr:
            duration = len(audio_float32) / self._native_sample_rate
            target_length = int(duration * target_sr)
            orig_indices = np.arange(len(audio_float32))
            target_indices = np.linspace(0, len(audio_float32) - 1, target_length)
            resampled_audio = np.interp(target_indices, orig_indices, audio_float32)
        else:
            resampled_audio = audio_float32

        # 2. Quantize float32 to int16 PCM
        clipped_audio = np.clip(resampled_audio, -1.0, 1.0)
        pcm_int16 = (clipped_audio * 32767.0).astype(np.int16)

        return pcm_int16.tobytes()

    def generate_pcm(self, text: str, voice: Optional[str] = None) -> Tuple[bytes, float]:
        """
        Synthesizes the entire text string into a single complete PCM byte buffer.

        :param text: Clean spoken text generated by DeepSeek
        :param voice: Kokoro voice ID (defaults to config.KOKORO_VOICE)
        :return: Tuple of (pcm_bytes, synthesis_time_ms)
        """
        if not self._pipeline:
            raise RuntimeError("Kokoro TTS pipeline is not initialized.")

        selected_voice = voice or config.KOKORO_VOICE
        start_time = time.time()
        logger.info(f"Synthesizing full speech [{selected_voice}]: \"{text[:50]}...\"")

        try:
            # Generate speech segments
            generator = self._pipeline(text, voice=selected_voice, speed=1.0)
            
            all_audio_chunks = []
            for _, _, audio in generator:
                if audio is not None and len(audio) > 0:
                    all_audio_chunks.append(audio)

            if not all_audio_chunks:
                logger.warning("Kokoro returned empty audio!")
                return b"", 0.0

            # Concatenate all sentence arrays and convert to 16-bit PCM bytes
            combined_float32 = np.concatenate(all_audio_chunks)
            pcm_bytes = self._resample_and_quantize(combined_float32)
            
            processing_time_ms = round((time.time() - start_time) * 1000, 2)
            audio_duration_sec = round(len(pcm_bytes) / (config.AUDIO_SAMPLE_RATE * 2), 2)

            logger.info("========== TTS SYNTHESIS SUCCESS ==========")
            logger.info(f"PCM Output Size : {len(pcm_bytes)} bytes ({audio_duration_sec}s audio)")
            logger.info(f"Processing Time : {processing_time_ms}ms")
            logger.info("===========================================")

            return pcm_bytes, processing_time_ms

        except Exception as e:
            logger.error(f"Error during TTS synthesis: {str(e)}")
            return b"", round((time.time() - start_time) * 1000, 2)

    def stream_pcm(self, text: str, voice: Optional[str] = None) -> Generator[bytes, None, None]:
        """
        Generator function that yields PCM audio chunks sentence-by-sentence.
        Allows the ESP32 speaker to start playing before the full text is synthesized!

        :param text: Clean spoken text generated by DeepSeek
        :param voice: Kokoro voice ID (defaults to config.KOKORO_VOICE)
        """
        if not self._pipeline:
            raise RuntimeError("Kokoro TTS pipeline is not initialized.")

        selected_voice = voice or config.KOKORO_VOICE
        logger.info(f"Starting real-time TTS audio stream [{selected_voice}]...")

        try:
            # Kokoro automatically splits long text into sentences/clauses
            generator = self._pipeline(text, voice=selected_voice, speed=1.0)
            
            for index, (_, _, audio) in enumerate(generator):
                if audio is not None and len(audio) > 0:
                    pcm_chunk = self._resample_and_quantize(audio)
                    logger.debug(f"Yielding sentence chunk #{index + 1} ({len(pcm_chunk)} bytes)")
                    yield pcm_chunk

            logger.info("TTS audio stream finished normally.")

        except Exception as e:
            logger.error(f"Error during TTS streaming: {str(e)}")


# Create an easily importable singleton instance
kokoro_service = KokoroService()
